baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clairenord.com" # the base hostname & protocol for your site

# Can't allow custom plugins on gh-pages (jekyll-pageless-redirects)
# safe: false

# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
gems:
  - jemoji
  - github-pages
  - jekyll-redirect-from

# Safe github pages thing
whitelist:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      author: "Claire Nord"
