# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-83054268-1'

menu:
- { name: "Blog", url: "/blog" }
- { name: "Classes", url: "/classes" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:cnord19@gmail.com'}
- {icon: 'github', link: 'https://github.com/cmnord'}
- {icon: 'book', link: 'https://www.goodreads.com/user/show/15765249-claire'}
- {icon: 'podcast', link: 'https://podyssey.fm/cnord'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/cmnord'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
